////
////  NewResourceViewModel.swift
////  CommunityResourceFinder
////
////  Created by Deke Bowman on 8/9/24.
////
//
//import Foundation
//
//
//class NewResourceViewModel: ObservableObject {
//    
//    @Published var newResource = NewResourceModel()
//    @Published var tags = [
//        "Menstrual health",
//        "Free Community Legal Assistance",
//        "Electricity",
//        "Farmers Markets",
//        "Prescription costs",
//        "Housing",
//        "Medicare/Medicaid/SSI",
//        "Lyft",
//        "Cell Phones",
//        "Free clothing",
//        "Behavioral Health",
//        "SNAP",
//        "Case Management & General Resources",
//        "Grief & Loss",
//        "Vision",
//        "Power",
//        "Mail Service",
//        "Identification services",
//        "Mental health crisis response team",
//        "Inpatient Rehab",
//        "Harm Reduction",
//        "Public Transit",
//        "Doctors",
//        "EBT",
//        "Outpatient Rehab",
//        "Transportation",
//        "Bike",
//        "Inpatient mental health treatment",
//        "P-EBT",
//        "Legal aid for homeowners",
//        "Personal Care Needs",
//        "Finding Doctors",
//        "Hygiene",
//        "Support Groups",
//        "Intellectual Disabilities",
//        "Free & low cost professional clothing",
//        "Food",
//        "Food Pantries",
//        "Resources for Seniors",
//        "Finding Therapy Options",
//        "Homelessness",
//        "Free & reduced Cost Health Clinics",
//        "City Council",
//        "Community Fridges",
//        "Water",
//        "WIC",
//        "HIV+ Resources",
//        "Furniture",
//        "Rideshare",
//        "Older Adults Meal Services",
//        "Veteran resources",
//        "Gas",
//        "Health",
//        "Diapers and Baby Supplies",
//        "LGBTQIA+ Resources",
//        "Legal Assistance",
//        "Mental health",
//        "AA",
//        "Utilities & taxes",
//        "Free meals",
//        "Tenants' Rights & Legal aid",
//        "AI-Anon",
//        "Substance Use & Addiction",
//        "Shoes",
//        "Other Health Insurance",
//        "Dental",
//        "Job training/development programs",
//        "Immigrant Services",
//        "Domestic Violence & Abuse",
//        "Feminine Products",
//        "Hot & Cold Weather Emergencies",
//        "Medical Bills",
//        "Employment & Finances",
//        "SEPTA",
//        "Suicide & crisis hotline",
//        "Human Trafficking",
//        "Christianity",
//        "Faith",
//        "Spiritual Guidance",
//        "Shelter"
//    ]
//    
//}
